### ISSUE TITLE
BIOS version 309

### ISSUE THREAD

**Issue by rogerdcarvalho** [shiecldk/ASUS-ZenBook-Pro-Duo-15-OLED-UX582-Hackintosh#5]
Your guide mentions BIOS version 303, but the device I bought (UX581) came with 309. When trying your EFI, I get a panic before setup even opens. I'm a bit hesitant to try modGRUBShell.efi with a different BIOS version. What do you reckon?

**Comment by rogerdcarvalho** [comment]
Never mind, got this working by making my own ACPI.

**Comment by shiecldk** [comment]
@rogerdcarvalho Nice! If you want, you can clone this project and make it to the UX581 project so that other people can work with you. (Remember to refer to this GitHub project. Thanks)
